# Generated by Django 4.2.1 on 2023-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='code',
        ),
    ]
